apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vinaylunawat/dot-net-CD.git
    targetRevision: HEAD
    path: GitOps/ArgoCD/environments/dev/cluster/ArgoCD/apps
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true



    automated:
      selfHeal: true
      prune: true
