apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../../../base/apps/guestbook/
images:
- name: 751111534101.dkr.ecr.us-west-2.amazonaws.com/demo-ecr
  newTag: 3309f1037b8fbf5590485e53ec11db5a2986ceba
