apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: 751111534101.dkr.ecr.us-west-2.amazonaws.com/demo-ecr:917f3425e3def220d74e9d230a8ac0065b4ee0a2
        name: guestbook-ui
        ports:
        - containerPort: 80
